import { expect, test, type Page } from '@playwright/test'
import { readFile } from 'node:fs/promises'

async function add(page: Page, word = 'substrate', meaning = '衬底') {
  await page.getByRole('button', { name: '＋ 添加词条', exact: true }).click()
  await page.getByLabel('英文词汇 / 短语').fill(word)
  await page.getByLabel('中文释义').fill(meaning)
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
}

async function state(page: Page) {
  return page.evaluate(async () => {
    const request = indexedDB.open('VocabularyDB')
    const db = await new Promise<IDBDatabase>((resolve, reject) => { request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error) })
    try {
      const transaction = db.transaction(['vocabulary', 'vocabularyAppMetadata'], 'readonly')
      const read = (store: string) => new Promise<unknown[]>((resolve, reject) => {
        const result = transaction.objectStore(store).getAll()
        result.onsuccess = () => resolve(result.result); result.onerror = () => reject(result.error)
      })
      const [entries, metadata] = await Promise.all([read('vocabulary'), read('vocabularyAppMetadata')])
      return { entries, metadata }
    } finally { db.close() }
  })
}

async function backup(page: Page) {
  const waiting = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出词库', exact: true }).click()
  const download = await waiting
  const buffer = await readFile((await download.path())!)
  return JSON.parse(buffer.toString()) as { version: number; app: string; exportedAt: string; entries: Record<string, unknown>[] }
}
async function select(page: Page, value: unknown) {
  await page.getByLabel('选择 JSON 备份').setInputFiles({ name: 'stage2-test.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(value)) })
  await expect(page.getByRole('dialog', { name: '导入预览' })).toBeVisible()
}

test('第二阶段备份状态、刷新和多标签页一致性，导出覆盖全库', async ({ page, context, baseURL }) => {
  await page.goto('./')
  const status = page.getByLabel('备份状态')
  await expect(status).toContainText('尚未发起导出')
  await expect(status).toContainText('当前词库为空')
  await expect(page.getByText('稍后提醒（7 天）', { exact: true })).toHaveCount(0)
  await add(page)
  await expect(status).toContainText('存在未导出变化')
  const second = await context.newPage()
  await second.goto(baseURL!)
  await add(second, 'impedance', '阻抗')
  await expect(page.getByRole('article')).toHaveCount(2)
  await page.getByRole('searchbox').fill('sub')
  const exported = await backup(page)
  expect(exported.entries).toHaveLength(2)
  expect(JSON.stringify(exported)).not.toMatch(/dataRevision|lastExportRequestedAt|VocabularyApp.backupState/)
  await expect(status).toContainText('自上次发起导出后无新增变化')
  await expect(second.getByLabel('备份状态')).toContainText('自上次发起导出后无新增变化')
  await page.reload()
  await expect(status).not.toContainText('尚未发起导出')
  await expect(page.getByRole('searchbox')).toHaveValue('')
  await second.getByRole('article', { name: 'impedance', exact: true }).getByRole('button', { name: '删除', exact: true }).click()
  await second.getByRole('button', { name: '永久删除', exact: true }).click()
  await expect(status).toContainText('存在未导出变化')
})

test('第二阶段导入预览取消只读、差异和并发重新确认', async ({ page, context, baseURL }) => {
  await page.goto('./'); await add(page)
  const exported = await backup(page)
  const existing = exported.entries[0]
  const value = { ...exported, entries: [
    { ...existing, meaning: '旧释义', note: '旧备注', status: 'mastered' },
    { ...existing, id: 'new', word: 'impedance', meaning: '阻抗' },
    { ...existing, id: 'file-duplicate', word: ' IMPEDANCE ', meaning: '文件内差异' },
    { ...existing, word: ' ' },
  ] }
  const before = await state(page)
  await select(page, value)
  const dialog = page.getByRole('dialog')
  await expect(dialog).toContainText('预计新增')
  await expect(dialog).toContainText('重复中存在差异 2 条')
  await dialog.getByText('查看重复词差异（2）', { exact: true }).click()
  await expect(dialog).toContainText('当前词库：衬底')
  await expect(dialog).toContainText('备份文件：旧释义')
  await page.keyboard.press('Escape')
  await expect(dialog).toHaveCount(0)
  expect(await state(page)).toEqual(before)
  await select(page, value)
  const second = await context.newPage()
  await second.goto(baseURL!); await add(second, 'impedance', '当前新释义')
  const afterOther = await state(second)
  await dialog.getByRole('button', { name: '确认合并', exact: true }).click()
  await expect(dialog).toContainText('已更新预览，本次未写入')
  expect(await state(page)).toEqual(afterOther)
  await dialog.getByRole('button', { name: '确认合并', exact: true }).click()
  await expect(page.getByText('成功导入：0；重复跳过：3；无效数据：1。', { exact: true })).toBeVisible()
  expect(await state(page)).toEqual(afterOther)
  await expect(page.getByRole('article', { name: 'impedance', exact: true })).toContainText('当前新释义')
})

test('第二阶段无结果预填、连续添加、重复保护与编辑边界', async ({ page }) => {
  await page.goto('./')
  await page.getByRole('searchbox').fill(' Anisotropic ')
  await page.getByRole('button', { name: '添加 “Anisotropic”', exact: true }).click()
  const word = page.getByLabel('英文词汇 / 短语')
  await expect(word).toHaveValue('Anisotropic')
  await page.getByLabel('中文释义').fill('各向异性')
  await page.getByLabel('备注').fill('测试语境')
  await page.getByRole('dialog').getByRole('combobox').selectOption('mastered')
  await page.getByRole('button', { name: '保存并继续添加', exact: true }).click()
  await expect(word).toHaveValue('')
  await expect(word).toBeFocused()
  await expect(page.getByLabel('中文释义')).toHaveValue('')
  await expect(page.getByLabel('备注')).toHaveValue('')
  await expect(page.getByRole('dialog').getByRole('combobox')).toHaveValue('learning')
  const before = await state(page)
  await word.fill('anisotropic'); await page.getByLabel('中文释义').fill('重复内容')
  await page.getByRole('button', { name: '保存并继续添加', exact: true }).click()
  await expect(page.getByRole('dialog').getByRole('alert')).toContainText('已经存在')
  await expect(word).toHaveValue('anisotropic')
  await expect(page.getByLabel('中文释义')).toHaveValue('重复内容')
  expect(await state(page)).toEqual(before)
  await word.fill('impedance'); await page.getByLabel('中文释义').fill('阻抗')
  await page.getByRole('button', { name: '保存并继续添加', exact: true }).click()
  await expect(word).toHaveValue('')
  await expect(page.getByRole('button', { name: '保存并继续添加', exact: true })).toBeEnabled()
  await page.keyboard.press('Escape')
  // 搜索+默认学习中筛选未显示已掌握词，仍必须检测全库重复。
  await page.getByRole('button', { name: '添加 “Anisotropic”', exact: true }).click()
  await page.getByLabel('中文释义').fill('筛选下重复')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('已经存在')
  await page.getByRole('button', { name: '查看已有词条', exact: true }).click()
  await page.getByRole('button', { name: '编辑词条', exact: true }).click()
  await expect(page.getByRole('button', { name: '保存并继续添加', exact: true })).toHaveCount(0)
  await page.keyboard.press('Escape')
})

test('第二阶段筛选单项清除、排序说明和搜索快捷键', async ({ page }) => {
  await page.goto('./'); await add(page)
  await add(page, 'electron', '电子')
  await page.getByRole('navigation').getByRole('button', { name: 'E', exact: true }).click()
  const search = page.getByRole('searchbox')
  await search.fill('ele')
  await page.getByLabel('词条排序').selectOption('count')
  await page.getByText('排序说明', { exact: true }).click()
  await expect(page.getByText('打开详情次数从多到少。指标相同时按英文名称和稳定 ID 排序。', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '清除搜索筛选', exact: true }).click()
  await expect(search).toHaveValue('')
  await expect(page.getByLabel('当前筛选')).toContainText('学习中')
  await expect(page.getByLabel('当前筛选')).toContainText('E')
  await page.getByRole('button', { name: '清除状态筛选', exact: true }).click()
  await expect(page.getByLabel('当前筛选')).not.toContainText('学习中')
  await page.getByRole('button', { name: '清除字母筛选', exact: true }).click()
  await expect(page.getByRole('article')).toHaveCount(2)
  await search.fill('sub')
  await page.locator('h1').click()
  await page.keyboard.press('Control+k')
  await expect(search).toBeFocused(); await expect(search).toHaveValue('sub')
  await page.getByRole('button', { name: '清除全部', exact: true }).click()
  await expect(page.getByLabel('词条排序')).toHaveValue('count')
  await page.getByRole('button', { name: '＋ 添加词条', exact: true }).click()
  await page.keyboard.press('Control+k')
  await expect(page.getByLabel('英文词汇 / 短语')).toBeFocused()
  await page.keyboard.press('Escape')
  await search.fill('sub'); await page.reload()
  await expect(search).toHaveValue('')
  await expect(page.getByLabel('当前筛选')).toContainText('学习中')
  await expect(page.getByLabel('词条排序')).toHaveValue('alphabet')
})

test('第二阶段中文 composition 和选词结束 Enter 不误提交，正常 Enter 保留', async ({ page }) => {
  await page.goto('./')
  await page.getByRole('button', { name: '＋ 添加词条', exact: true }).click()
  const word = page.getByLabel('英文词汇 / 短语')
  await word.fill('substrate'); await page.getByLabel('中文释义').fill('衬底')
  await word.focus()
  await word.dispatchEvent('compositionstart', { data: '衬' })
  await page.keyboard.press('Enter')
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByRole('article')).toHaveCount(0)
  await word.evaluate(element => {
    element.dispatchEvent(new CompositionEvent('compositionend', { bubbles: true, data: '衬底' }))
    const enter = new KeyboardEvent('keydown', { key: 'Enter', isComposing: false, bubbles: true, cancelable: true })
    element.dispatchEvent(enter)
    if (!enter.defaultPrevented) throw new Error('选词尾部 Enter 未被保护')
    element.closest('form')!.requestSubmit()
  })
  await expect(page.getByRole('article')).toHaveCount(0)
  await page.waitForTimeout(120)
  await page.keyboard.press('Enter')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('article')).toHaveCount(1)
  const search = page.getByRole('searchbox')
  await search.fill('衬底')
  await search.dispatchEvent('compositionstart', { data: '衬底' })
  await page.keyboard.press('Enter')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('article')).toContainText('查看 0 次')
  await search.dispatchEvent('compositionend', { data: '衬底' })
})

test('第二阶段 HTTPS/localhost 复制正确与失败、不支持反馈', async ({ page, context, baseURL }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'], { origin: new URL(baseURL!).origin })
  await page.goto('./'); await add(page)
  await page.getByRole('article').getByRole('button', { name: 'substrate', exact: true }).click()
  await page.getByRole('button', { name: '复制英文', exact: true }).click()
  await expect(page.getByRole('dialog').getByRole('status')).toHaveText('已复制')
  expect(await page.evaluate(() => navigator.clipboard.readText())).toBe('substrate')
  await page.getByRole('button', { name: '复制中文释义', exact: true }).click()
  expect(await page.evaluate(() => navigator.clipboard.readText())).toBe('衬底')
  await page.evaluate(() => { Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: () => Promise.reject(new Error('denied')) } }) })
  await page.getByRole('button', { name: '复制英文', exact: true }).click()
  await expect(page.getByRole('dialog').getByRole('alert')).toContainText('复制失败')
  await page.evaluate(() => { Object.defineProperty(navigator, 'clipboard', { configurable: true, value: undefined }) })
  await page.getByRole('button', { name: '复制中文释义', exact: true }).click()
  await expect(page.getByRole('dialog').getByRole('alert')).toContainText('不支持复制')
  await page.getByRole('button', { name: '编辑词条', exact: true }).click()
  await expect(page.getByLabel('中文释义')).toHaveValue('衬底')
})

test('第二阶段真实 v1 升级、应用命名空间和其他应用数据保留', async ({ page, baseURL }) => {
  await page.goto(new URL('favicon.svg', baseURL!).href)
  const legacy = await page.evaluate(async () => {
    const open = (name: string, version: number, upgrade: (db: IDBDatabase) => void) => new Promise<IDBDatabase>((resolve, reject) => {
      const request = indexedDB.open(name, version)
      request.onupgradeneeded = () => upgrade(request.result)
      request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error)
    })
    const other = await open('OtherApp.test', 1, db => db.createObjectStore('settings'))
    const otherTx = other.transaction('settings', 'readwrite')
    otherTx.objectStore('settings').put('keep-me', 'sentinel')
    await new Promise<void>(resolve => { otherTx.oncomplete = () => resolve() }); other.close()
    localStorage.setItem('OtherApp.settings', 'keep-me')
    sessionStorage.setItem('OtherApp.session', 'keep-me')
    const db = await open('VocabularyDB', 1, db => {
      const table = db.createObjectStore('vocabulary', { keyPath: 'id' })
      table.createIndex('normalizedWord', 'normalizedWord', { unique: true })
      for (const key of ['status', 'createdAt', 'lastSearchedAt']) table.createIndex(key, key)
    })
    const row = { id: 'legacy-browser', word: 'substrate', meaning: '旧词库释义', note: '旧备注', status: 'learning', normalizedWord: 'substrate',
      searchCount: 7, createdAt: '2025-01-01T00:00:00.000Z', updatedAt: '2025-02-02T00:00:00.000Z', lastSearchedAt: '2026-10-01T00:00:00.000Z' }
    const transaction = db.transaction('vocabulary', 'readwrite')
    transaction.objectStore('vocabulary').add(row)
    await new Promise<void>((resolve, reject) => { transaction.oncomplete = () => resolve(); transaction.onerror = () => reject(transaction.error) })
    db.close(); return row
  })
  await page.goto(baseURL!)
  await expect(page.getByRole('article', { name: 'substrate', exact: true })).toContainText('旧词库释义')
  const migrated = await state(page)
  expect(migrated.entries).toEqual([legacy])
  expect(migrated.metadata).toEqual([expect.objectContaining({ key: 'VocabularyApp.backupState', dataRevision: 1, lastExportedRevision: 0 })])
  const exported = await backup(page)
  expect(exported.entries[0]).toMatchObject({ id: legacy.id, searchCount: 7, note: '旧备注', updatedAt: legacy.updatedAt })
  const untouched = await page.evaluate(async () => {
    const request = indexedDB.open('OtherApp.test')
    const db = await new Promise<IDBDatabase>(resolve => { request.onsuccess = () => resolve(request.result) })
    const read = db.transaction('settings', 'readonly').objectStore('settings').get('sentinel')
    const value = await new Promise<unknown>(resolve => { read.onsuccess = () => resolve(read.result) }); db.close()
    return { value, local: localStorage.getItem('OtherApp.settings'), session: sessionStorage.getItem('OtherApp.session'),
      localNames: Object.keys(localStorage), sessionNames: Object.keys(sessionStorage) }
  })
  expect(untouched).toEqual({ value: 'keep-me', local: 'keep-me', session: 'keep-me', localNames: ['OtherApp.settings'], sessionNames: ['OtherApp.session'] })
})

test('第二阶段提醒暂停跨刷新保留，下载请求失败不伪造导出', async ({ page }) => {
  await page.goto('./'); await add(page)
  await page.evaluate(async () => {
    const request = indexedDB.open('VocabularyDB')
    const db = await new Promise<IDBDatabase>(resolve => { request.onsuccess = () => resolve(request.result) })
    const transaction = db.transaction('vocabularyAppMetadata', 'readwrite')
    const store = transaction.objectStore('vocabularyAppMetadata')
    const reading = store.get('VocabularyApp.backupState')
    reading.onsuccess = () => store.put({ ...reading.result, firstPendingContentAt: '2026-01-01T00:00:00.000Z' })
    await new Promise<void>(resolve => { transaction.oncomplete = () => resolve() }); db.close()
  })
  await page.reload()
  const close = page.getByRole('button', { name: '稍后提醒（7 天）', exact: true })
  await expect(close).toBeVisible()
  const before = await state(page)
  await close.click()
  await expect(close).toHaveCount(0)
  await page.reload(); await expect(close).toHaveCount(0)
  const snoozed = await state(page)
  expect(snoozed.entries).toEqual(before.entries)
  expect(snoozed.metadata[0]).toMatchObject({ dataRevision: 1, lastExportedRevision: 0, reminderDismissedUntil: expect.any(String) })
  await page.evaluate(() => { URL.createObjectURL = () => { throw new Error('download blocked') } })
  await page.getByRole('button', { name: '导出词库', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('未能发起 JSON 下载')
  expect(await state(page)).toEqual(snoozed)
  await expect(page.getByLabel('备份状态')).toContainText('尚未发起导出')
})

test('第二阶段连续保存失败保留内容，360px 预览、复制和筛选可操作', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 360, height: 900 })
  await page.goto('./'); await add(page)
  const exported = await backup(page)
  await select(page, { ...exported, entries: [{ ...exported.entries[0], meaning: '备份差异' }] })
  await page.getByText('查看重复词差异（1）', { exact: true }).click()
  expect(await page.getByRole('dialog').evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('stage2-preview-360.png'), fullPage: true })
  await page.getByRole('button', { name: '取消', exact: true }).click()
  await page.getByRole('article').getByRole('button', { name: 'substrate', exact: true }).click()
  await expect(page.getByRole('button', { name: '复制英文', exact: true })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('stage2-detail-360.png'), fullPage: true })
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: '清除状态筛选', exact: true }).click()
  await page.getByRole('button', { name: '＋ 添加词条', exact: true }).click()
  await page.getByLabel('英文词汇 / 短语').fill('impedance')
  await page.getByLabel('中文释义').fill('阻抗')
  const before = await state(page)
  await page.evaluate(() => { IDBObjectStore.prototype.add = () => { throw new DOMException('full', 'QuotaExceededError') } })
  await page.getByRole('button', { name: '保存并继续添加', exact: true }).click()
  await expect(page.getByRole('dialog').getByRole('alert')).toContainText('保存失败')
  await expect(page.getByLabel('英文词汇 / 短语')).toHaveValue('impedance')
  await expect(page.getByLabel('中文释义')).toHaveValue('阻抗')
  expect(await state(page)).toEqual(before)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('stage2-form-360.png'), fullPage: true })
  await page.keyboard.press('Escape')
  await page.screenshot({ path: testInfo.outputPath('stage2-home-360.png'), fullPage: true })
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.screenshot({ path: testInfo.outputPath('stage2-home-1440.png'), fullPage: true })
})
